---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu
    image: ubuntu
    exposed_ports:
      - 8443/tcp
      - 22/tcp
    published_ports:
      - 0.0.0.0:443:8443
  - name: centos
    image: centos
    exposed_ports:
      - 8443/tcp
      - 22/tcp
provisioner:
  name: ansible
verifier:
  name: ansible
