---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu
    image: ubuntu
    exposed_ports:
      - 8080/tcp
    published_ports:
      - 0.0.0.0:8080:8080/tcp
provisioner:
  name: ansible
verifier:
  name: ansible
