---
# tasks file for java
- name: Include package name as variable for the different OS
  include_vars: "{{ item }}"
  with_first_found :
    - "{{ ansible_distribution}}.yml"
    - main.yml
 
- name: Install java
  package: 
   name: "{{ java_package_name }}"
   state: present
