---
- name : get jenkins apt key on CentOS
  get_url :
    url : https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: add entry on CentOS
  shell: rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
