---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu
    image: ubuntu
  - name: debian
    image: debian
  - name: centos
    image: centos
provisioner:
  name: ansible
verifier:
  name: ansible
