---
# tasks file for docker

- name: add necessary package on debian based
  apt:
    update_cache: yes
    name: "{{ item }}"
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name: add necessary package on centos
  yum:
    name: "{{ item }}"
  loop:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
  when: ansible_distribution == "CentOS"

- name: add key on debian based
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name: get version on debian based
  shell: lsb_release -cs
  register: version
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name: add repo on ubuntu
  apt_repository:
    repo: deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ version.stdout }} stable
    state: present
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name: add repo on centos
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  when: ansible_distribution == "CentOS"

- name: Install docker
  package:
    update_cache: yes
    name: "{{ item }}"
    state: present
  loop:
    - containerd.io
    - docker-ce-cli
    - docker-ce

